### ISSUE TITLE
Éric Vyncke's feedback (1 or 2): SVCB

### ISSUE THREAD

**Issue by richsalz** [richsalz/draft-ietf-uta-rfc6125bis#98]
I find this document update useful ***BUT*** it lacks the support of the new
SVCB (draft-ietf-dnsop-svcb-https)... May I recommend that this document is
sent back to the WG in order to incorporate the SCVB (it is very similar to SRV
IMHO)? I appreciate that the SVCB started in a different WG hence the
disconnect even if some authors of the two I-Ds have the same affiliation ;-) I
added the SVCB authors in copy to this ballot, just in case.

**Comment by enygren** [comment]
At least for HTTPS the SVCB record does not have the same special-handling that SRV has.
In particular, the draft in the RFC editor queue (draft-ietf-dnsop-svcb-https-12) has:

> Note that none of these forms alter the origin or authority for validation purposes. For example, TLS clients MUST continue to validate TLS certificates for the original service name.
> ...
> Note that none of these forms alter the HTTPS origin or authority. For example, clients MUST continue to validate TLS certificate hostnames based on the origin.
> ...
> Similar to CNAME, HTTPS RRs have no impact on the origin name. When connecting, clients will continue to treat the authoritative origins as "https://www.aliased.example" and "https://aliased.example", respectively, and will validate TLS server certificates accordingly.

For HTTPS RRs it's pretty clear that just DNS-IDs would be used in this case and that AliasMode and TargetNames would not have any influence.

It is an interesting point that while this is fairly clear for HTTPS RRs not using alternate ports, the SVCB draft is less clear on how this fits in or what is desirable for SVCB lookups of the form _8080._foo.example.com and what would be the "original service name" in that case.  Would these want to also be SRV-IDs?  

Even with HTTPS RRs with Web Origins on alternate ports (eg, "https://example.com:8443"), how to handle _8443._https.example.com is less clear.  To be non-breaking, example.com as a DNS-ID might still be needed.

Would it make sense to also allow the SRV-IDs in this case (eg, "_8080._foo.example.com") but to be clear that unlike SRV these don't carry through to TargetName and/or through AliasMode?

(It would be good to loop Ben Schwartz in here as well since he has thought about this part lots as well.  There may be people we want to include in the discussion for going past the HTTPS use-case.)

**Comment by richsalz** [comment]
Ping @bemasc

**Comment by enygren** [comment]
Taking a deeper read through draft-ietf-uta-rfc6125bis, some of this may be generalizing to also be clear that protocols using SVCB (or SVCB-compatible record  types) need to define their validation rules and what identifiers are allowed.  (Similar to what the draft says for other protocols.)

**Comment by richsalz** [comment]
Yes, I am thinking -- if only for simplicity -- we say something like this:
```
Anything other than a simple origin name is out of scope for this specification.
Protocols that use identifiers that look like SRV IDs, for example, must define their
own rules.
```

**Comment by bemasc** [comment]
Defining WebPKI integration rules generally for all future protocols and ID types sounds very hard.

I'm not sure whether "https://example.com:12345" looks like an SRV ID (or a URI ID) or not, so I'm not sure what to make of that rule.

I think the truth is:

> Use of SVCB-compatible records during connection establishment does not alter any PKIX validation requirements unless the applicable SVCB mapping document states otherwise.  For example, the PKIX validation rules for HTTP over TLS {{?RFC2818}} and DNS over TLS {{?RFC7858}} do not change when the client uses HTTPS records {{?I-D.ietf-dnsop-svcb-https}} or SVCB for DNS {{?I-D.ietf-add-svcb-dns}}.

That's a bit squishy but anything else seems a bit speculative.

**Comment by richsalz** [comment]
@bemasc I like your suggestion.  @stpeter , do you want to make a PR that integrates this (and the appropriate refernces) or me?

**Comment by stpeter** [comment]
Yes, I will create a PR.

**Comment by stpeter** [comment]
Now see https://github.com/richsalz/draft-ietf-uta-rfc6125bis/pull/102 - feedback welcome.
